# -*- coding: utf-8 -*-
"""AI medical assistance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157gH3VpBIGTngIT4qB8HpBItQtsathEr
"""

import pandas as pd

df=pd.read_csv('/content/Diabetes_prediction.csv')
df

df.isna().sum()

df.dtypes

x=df.iloc[:,:-1]
x

y=df.iloc[:,-1]
y

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_scaled=scaler.fit_transform(x)
x_scaled

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.3,random_state=1)

x_train.shape,y_train.shape

x_test.shape,y_test.shape

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

from sklearn.metrics import accuracy_score, classification_report
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

from sklearn.metrics import accuracy_score, classification_report
print("Accuracy:",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

lr = LogisticRegression()
lr.fit(x_train, y_train)
lr_pred = lr.predict(x_test)
lr_acc = accuracy_score(y_test, lr_pred)

dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
dt_pred = dt.predict(x_test)
dt_acc = accuracy_score(y_test, dt_pred)

rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf_pred = rf.predict(x_test)
rf_acc = accuracy_score(y_test, rf_pred)

print("Logistic Regression:", lr_acc)
print("Decision Tree:", dt_acc)
print("Random Forest:", rf_acc)

models = {
    "Logistic Regression": lr_acc,
    "Decision Tree": dt_acc,
    "Random Forest": rf_acc
}

best_model = max(models, key=models.get)

print("Best Model:", best_model)
print("Best Accuracy:", models[best_model])

from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense
cnn_model = Sequential()
cnn_model.add(Conv2D(32,(3,3),activation='relu',input_shape=(150,150,3)))
cnn_model.add(MaxPool2D((2,2)))
cnn_model.add(Conv2D(64,(3,3),activation='relu'))
cnn_model.add(MaxPool2D((2,2)))
cnn_model.add(Flatten())
cnn_model.add(Dense(128,activation='relu'))
categories = ['NORMAL', 'PNEUMONIA']
cnn_model.add(Dense(len(categories),activation='softmax'))

cnn_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

import os
import numpy as np
from skimage.io import imread
from skimage.transform import resize

from google.colab import drive
drive.mount('/content/drive')

X_train = []
y_train = []
datapath = "/content/drive/MyDrive/chest xrays/train"
categories = ['NORMAL', 'PNEUMONIA']

for category in categories:
    path = os.path.join(datapath, category)

    for image in os.listdir(path):
        img_path = os.path.join(path, image)

        img = imread(img_path)
        img = resize(img, (150,150,3))

        X_train.append(img)
        y_train.append(categories.index(category))

    print("Loaded:", category)

import numpy as np

X_train = np.array(X_train)
y_train = np.array(y_train)

cnn_model.fit(X_train, y_train, epochs=10)

print(img.shape)

import numpy as np
x=np.array(x_train)
y=np.array(y_train)

print(x_train.shape)

print(X_train.shape)
print(y_train.shape)

cnn_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = cnn_model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=8,
    validation_split=0.2
)

print(history.history['accuracy'])

from skimage.io import imread
from skimage.transform import resize
import numpy as np
img = imread("/content/NORMAL2-IM-0290-0001.jpeg")
img = resize(img, (150,150,3))
img = np.expand_dims(img, axis=0)
print(img.shape)

pred = cnn_model.predict(img)
print(pred)

prediction = categories[np.argmax(pred)]
print(prediction)

print("Predicted Class:", categories[np.argmax(pred)])

!ls /content

from skimage.io import imread
from skimage.transform import resize
import numpy as np
img = imread("/content/NORMAL2-IM-0290-0001.jpeg")
img = resize(img, (150,150,3))
print(img.shape)

img = np.expand_dims(img, axis=0)
print(img.shape)

print("Predicted Class:", categories[np.argmax(pred)])

!pip install -q google-generativeai

import google.generativeai as genai

import os
import google.generativeai as genai
from google.colab import userdata

API_KEY = userdata.get('YOUR_API_KEY_HERE')
genai.configure(api_key=API_KEY)

model = genai.GenerativeModel("models/gemini-3.1-flash-lite")
response = model.generate_content("What is diabetes?")
print(response.text)

prompt = f"""
The chest X-ray prediction is {prediction}.

Explain this result in simple language for a patient.
Mention that this is an AI prediction and not a final medical diagnosis.
"""

response = model.generate_content(prompt)

print(response.text)

cnn_model.save("medical_cnn_model.h5")